unique_ids:
  forms:
    MENU: '1713340964538439840272143.6017'
  modules: {}
  server_modules: {}
  assets:
    standard-page.html: GXB5DZODBGBALWAN32ILQJ4JTV367YVU
    theme.css: QIHLWIBS66LB4RE6U34U5C6XGQMHEP4Y
