roles: []
color_scheme:
  colors:
  - {name: Sky blue, color: '#5DADE2'}
  - {name: Emerald, color: '#000000'}
  - {name: Sunflower, color: '#000000'}
  - {name: Silver white, color: '#000000'}
  - {name: Charcoal, color: '#000000'}
  preset_groups: []
